### PR TITLE
remove reflection

### PR DESCRIPTION
**Pull request by MichaelBlume**

### CODE REVIEW

**Comment by pyr** [comment]
I'd love to see a release with this in, if at all possible. (ideally depending on a newer release of flatland/ordered, once a new release with amalloy/ordered#30 goes out).

**Comment by MichaelBlume** [comment]
Anything I can do to help get this merged?

**Comment by marcomorain** [comment]
Thanks @MichaelBlume @pyr - sorry the delay on this (A YEAR!)

**Comment by pyr** [comment]
@marcomorain awesome, thanks!

**Pull request merged**
